#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ ( "$SHLVL" -eq 1 && ! -o LOGIN ) && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

#Set env vars
typeset -U path
#Include bin in path
path=(~/bin $path[@])

#Rust
export PATH=${PATH}:${HOME}/.cargo/bin

#Ruby (ew)
export PATH=${PATH}:${HOME}/.gem/ruby/2.4.0/bin

#Editors
export EDITOR='nvim'
export VISUAL='nvim'
export PAGER='less'
